name: spryagatel
description: A Russian verb conjugator.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0 < 3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons:
  isar: ^1.0.5
  isar_flutter_libs: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  arb_generator:
  flutter_lints:
  flutter_pseudolocalizor:
  intl_utils: ^2.6.0
  isar_generator: ^1.0.5
  build_runner:

flutter:
  uses-material-design: true

arb_generator:
  input_filepath: "assets_dev/loca/loca.csv"
  output_directory: "assets_dev/l10n"
  filename_prepend: "intl_"
  csv_settings:
    delimiter: ";"
    description_index: 1
    base_index: 2

flutter_pseudolocalizor:
  input_filepath: "assets_dev/l10n/intl_en.arb"
  replace_base: false
  use_brackets: true
  text_expansion_format: 'repeatVowels'
  text_expansion_ratio: null
  languages_to_generate:
    - de
  arb_settings:
    output_directory: 'assets_dev/l10n_pseudo'

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: assets_dev/l10n_pseudo
  output_dir: lib/generated
